# -*- coding: utf-8 -*-
"""analisis_hibrido_vs_genetico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f27sYRa1OwhuqSM4LkC4rm4MLEiafOX8
"""

import pandas as pd
import matplotlib.pyplot as plt

# Cargar los archivos CSV
dfh = pd.read_csv('hibrido_r.csv')
dfg = pd.read_csv('genetico_r.csv')

dfh.columns = ['Hibrido']
dfg.columns = ['Genetico']

neodf = pd.concat([dfh, dfg], axis=1)

print(neodf)

plt.figure(figsize=(10, 5))
plt.plot(neodf['Hibrido'], label='Híbrido', c='lime')
plt.plot(neodf['Genetico'], label='Genético', c='purple')
plt.xlabel('Iteración')
plt.ylabel('Fitness')
plt.title('Comparación de Metaheurísticos - Gráfico de Líneas')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 5))
plt.scatter(neodf.index, neodf['Hibrido'], label='Híbrido', c='lime')
plt.scatter(neodf.index, neodf['Genetico'], label='Genético', c='purple')
plt.xlabel('Iteración')
plt.ylabel('Fitness')
plt.title('Comparación de Metaheurísticos - Gráfico de Dispersión')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 5))
neodf.boxplot(column=['Hibrido', 'Genetico'])
plt.title('Comparación de Metaheurísticos - Box Plot')
plt.ylabel('Fitness')
plt.show()

plt.figure(figsize=(10, 5))
plt.hist(neodf['Hibrido'], bins=20, alpha=0.5, label='Híbrido', color='lime')
plt.hist(neodf['Genetico'], bins=20, alpha=0.5, label='Genético', color='purple')
plt.xlabel('Fitness')
plt.ylabel('Frecuencia')
plt.title('Comparación de Metaheurísticos - Histograma')
plt.legend()
plt.show()